/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;


import logica.Jugador;

/**
 *
 * @author dixia
 */
public class DlgDatosJu extends javax.swing.JDialog {

    private Jugador jugador;

    /**
     * Creates new form DlgDatosJu
     *
     * @param parent
     * @param modal
     */
    public DlgDatosJu(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.jugador = new Jugador();
    }

    /**
     * Constructor que recibe un objeto jugador
     *
     * @param parent
     * @param modal
     * @param jugador
     */
    public DlgDatosJu(java.awt.Frame parent, boolean modal, Jugador jugador) {
        super(parent, modal);
        initComponents();
        this.jugador = jugador;
        this.setTitle("Datos de jugador " + jugador.getNombre());
        this.cargarDatos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNombre = new javax.swing.JLabel();
        txtDNombre = new javax.swing.JTextField();
        lblTelefono = new javax.swing.JLabel();
        txtDTelefono = new javax.swing.JTextField();
        lblMonto = new javax.swing.JLabel();
        txtDMontoI = new javax.swing.JTextField();
        lblDireccion = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDDireccion = new javax.swing.JTextArea();
        lblDCarton = new javax.swing.JLabel();
        txtDCarton = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblNumeros = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnRegresar = new javax.swing.JButton();
        txtDCedula = new javax.swing.JTextField();
        lblCedula = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Jugador");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNombre.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNombre.setText("Nombre:");
        getContentPane().add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 103, 44));

        txtDNombre.setEditable(false);
        getContentPane().add(txtDNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 300, -1));

        lblTelefono.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTelefono.setText("Teléfono:");
        getContentPane().add(lblTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 103, 44));

        txtDTelefono.setEditable(false);
        getContentPane().add(txtDTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 300, -1));

        lblMonto.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblMonto.setText("Monto Inicial:");
        getContentPane().add(lblMonto, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 103, 44));

        txtDMontoI.setEditable(false);
        getContentPane().add(txtDMontoI, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, 147, -1));

        lblDireccion.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblDireccion.setText("Dirección:");
        getContentPane().add(lblDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 103, 44));

        txtDDireccion.setEditable(false);
        txtDDireccion.setColumns(20);
        txtDDireccion.setRows(5);
        jScrollPane1.setViewportView(txtDDireccion);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, 300, -1));

        lblDCarton.setText("N° Cartón:");
        getContentPane().add(lblDCarton, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 210, -1, 20));

        txtDCarton.setEditable(false);
        getContentPane().add(txtDCarton, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 210, 78, -1));

        tblNumeros.setBackground(new java.awt.Color(255, 255, 255));
        tblNumeros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "# 1", "# 2", "# 3", "# 4", "# 5", "#6", "#7", "#8", "#9", "#10"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblNumeros.setGridColor(new java.awt.Color(204, 204, 204));
        tblNumeros.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblNumeros.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblNumeros.setShowGrid(true);
        jScrollPane3.setViewportView(tblNumeros);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, 480, 50));

        jLabel1.setText("Números seleccionados");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 370, -1, -1));

        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 461, -1, 40));

        txtDCedula.setEditable(false);
        getContentPane().add(txtDCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 300, -1));

        lblCedula.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCedula.setText("Cédula:");
        getContentPane().add(lblCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 103, 44));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    /**
     * @param args the command line arguments
     */
       
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DlgDatosJu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DlgDatosJu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DlgDatosJu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DlgDatosJu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                DlgDatosJu dialog = new DlgDatosJu(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblCedula;
    private javax.swing.JLabel lblDCarton;
    private javax.swing.JLabel lblDireccion;
    private javax.swing.JLabel lblMonto;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JTable tblNumeros;
    private javax.swing.JTextField txtDCarton;
    private javax.swing.JTextField txtDCedula;
    private javax.swing.JTextArea txtDDireccion;
    private javax.swing.JTextField txtDMontoI;
    private javax.swing.JTextField txtDNombre;
    private javax.swing.JTextField txtDTelefono;
    // End of variables declaration//GEN-END:variables

    private void cargarDatos() {
        
        txtDCarton.setText(jugador.getNumCarton()+"");
        txtDCedula.setText(jugador.getCedula()+"");
        txtDTelefono.setText(jugador.getTelefono()+"");
        txtDDireccion.setText(jugador.getDireccion());
        txtDMontoI.setText(jugador.getMontoIni()+"");
        txtDNombre.setText(jugador.getNombre());
        
        for (int i = 0; i < jugador.getNumSelec().length; i++) {
            tblNumeros.setValueAt(jugador.getNumSelec()[i], 0, i);
        }
    }
}
